#!/usr/bin/env python3
"""Generate the CMake view of the vendored core's build spec.

Why this exists: the core's file list lives in exactly one place upstream --
`third_party/fceumm_next/Makefile.common`. Hand-copying 648 sources into a
CMakeLists.txt is how mappers silently disappear from an Android build, so we
instead ask the desktop test Makefile (which includes that fragment) to print
what it compiles, and write the answer into a committed .cmake file.

`--check` re-derives the spec and fails if the committed file no longer matches,
which is what makes the list auditable in CI instead of merely generated once.
"""
import argparse
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CPP = os.path.join(REPO, "engine", "src", "main", "cpp")
TEST_DIR = os.path.join(REPO, "engine", "src", "test", "native")
OUT_REL = os.path.join("engine", "src", "main", "cpp", "fceumm_build_spec.cmake")
BRIDGE_REL = "bridge/fceumm/mariobox_fceumm_ext.c"


def rel(path):
    """Repo-relative paths keep the generated file diff-friendly and relocatable."""
    p = os.path.normpath(path.strip())
    r = os.path.relpath(p, REPO)
    return r if not r.startswith("..") else p


def spec():
    out = subprocess.run(["make", "-s", "-C", TEST_DIR, "print-build-spec"],
                         capture_output=True, text=True, check=True).stdout
    srcs, incs, defs, force = [], [], [], []
    for line in out.splitlines():
        if "\t" not in line:
            continue
        kind, val = line.split("\t", 1)
        if kind == "src":
            srcs.append(rel(val))
        elif kind == "inc":
            v = rel(val)
            if v not in incs:
                incs.append(v)
        elif kind == "def":
            if val.strip() and val.strip() not in defs:
                defs.append(val.strip())
        elif kind == "force_include":
            force.append(rel(val))
    return srcs, incs, defs, force


HEADER = (
    "# Generated by tools/gen_cmake_core_list.py -- do not edit by hand.\n"
    "#\n"
    "# The vendored core keeps its source list in third_party/fceumm_next/Makefile.common;\n"
    "# this file is that list as CMake sees it, so the Android build compiles exactly what\n"
    "# the (green) desktop host tests compile. Re-run the generator after touching the\n"
    "# vendored core, or run `make -C engine/src/test/native check-source-list` to verify.\n"
)


def render(srcs, incs, defs, force):
    def lst(name, items, quote=True):
        lines = ["set(%s" % name]
        for it in items:
            lines.append('  "%s"' % it if quote else "  %s" % it)
        lines.append(")")
        return "\n".join(lines) + "\n"

    body = [HEADER]
    body.append("# Paths are relative to engine/src/main/cpp (this file's directory).\n")
    body.append(lst("MBCORE_FCEUMM_SOURCES", [os.path.relpath(os.path.join(REPO, s), CPP) for s in srcs]))
    body.append(lst("MBCORE_FCEUMM_INCLUDES", [os.path.relpath(os.path.join(REPO, s), CPP) for s in incs]))
    body.append(lst("MBCORE_FCEUMM_DEFINES", defs, quote=True))
    body.append(lst("MBCORE_FCEUMM_FORCE_INCLUDES",
                    [os.path.relpath(os.path.join(REPO, s), CPP) for s in force]))
    return "\n".join(body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()
    srcs, incs, defs, force = spec()
    text = render(srcs, incs, defs, force)
    path = os.path.join(REPO, OUT_REL)
    if args.check:
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if old != text:
            print("ERROR: %s is stale; run `python3 tools/gen_cmake_core_list.py`" % OUT_REL,
                  file=sys.stderr)
            return 1
        print("ok: %s matches Makefile.common (%d sources)" % (OUT_REL, len(srcs)))
        return 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s: %d sources, %d includes, %d defines" % (OUT_REL, len(srcs), len(incs), len(defs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
